// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Answer interface {
	IsAnswer()
}

type Question interface {
	IsQuestion()
}

type AddQuestionAnswer struct {
	Value string `json:"value"`
}

type ChoiceQuestion struct {
	ID      string    `json:"id"`
	Body    string    `json:"body"`
	Weight  float64   `json:"weight"`
	Options []*Option `json:"options"`
}

func (ChoiceQuestion) IsQuestion() {}

type Option struct {
	ID     string  `json:"id"`
	Body   string  `json:"body"`
	Weight float64 `json:"weight"`
}

type QuestionAnswer struct {
	ID         string `json:"id"`
	Value      string `json:"value"`
	QuestionID string `json:"questionID"`
}

func (QuestionAnswer) IsAnswer() {}

type TextQuestion struct {
	ID     string  `json:"id"`
	Body   string  `json:"body"`
	Weight float64 `json:"weight"`
}

func (TextQuestion) IsQuestion() {}
